name: Full Auto Deploy Node.js + Flask (Single Root Repo) to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create major.pem from secret
      run: |
        echo "${{ secrets.AWS_SSH_KEY }}" > major.pem
        chmod 400 major.pem

    - name: Update Node.js to v20
      env:
        EC2_PUBLIC_IP: ${{ secrets.AWS_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no -i major.pem ubuntu@$EC2_PUBLIC_IP "curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - && sudo apt install -y nodejs"

    - name: Install Dependencies and Configure Nginx
      env:
        EC2_PUBLIC_IP: ${{ secrets.AWS_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no -i major.pem ubuntu@$EC2_PUBLIC_IP << 'EOF'
        sudo apt update -y
        sudo apt install -y nginx python3 python3-pip
        sudo npm install -g pm2
        sudo systemctl start nginx
        sudo systemctl enable nginx
        EOF

    - name: Clone Project Files from GitHub Repo
      env:
        EC2_PUBLIC_IP: ${{ secrets.AWS_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no -i major.pem ubuntu@$EC2_PUBLIC_IP << 'EOF'
        cd /home/ubuntu
        git clone https://github.com/your-username/your-repo.git project
        cd project
        git pull origin main
        EOF

    - name: Install Backend Dependencies and Fix Vulnerabilities
      env:
        EC2_PUBLIC_IP: ${{ secrets.AWS_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no -i major.pem ubuntu@$EC2_PUBLIC_IP << 'EOF'
        cd /home/ubuntu/project
        npm install
        npm audit fix --force || true
        EOF

    - name: Start Backend Application
      env:
        EC2_PUBLIC_IP: ${{ secrets.AWS_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no -i major.pem ubuntu@$EC2_PUBLIC_IP << 'EOF'
        cd /home/ubuntu/project
        pm2 delete nodeapp || true
        pm2 start app.js --name nodeapp
        EOF

    - name: Copy Nginx Configuration to EC2
      env:
        EC2_PUBLIC_IP: ${{ secrets.AWS_HOST }}
      run: |
        scp -i major.pem ./nginx.conf ubuntu@$EC2_PUBLIC_IP:/home/ubuntu/project/nginx.conf

    - name: Configure Nginx to Serve Application
      env:
        EC2_PUBLIC_IP: ${{ secrets.AWS_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no -i major.pem ubuntu@$EC2_PUBLIC_IP << 'EOF'
        sudo cp /home/ubuntu/project/nginx.conf /etc/nginx/sites-available/project-app
        sudo ln -s /etc/nginx/sites-available/project-app /etc/nginx/sites-enabled/
        sudo nginx -t
        sudo systemctl reload nginx
        EOF

    - name: Remove major.pem
      if: always()
      run: |
        rm -f major.pem
