name: Full Auto Deploy Node.js + Flask (Single Root Repo) to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          # Update and install packages
          sudo apt update && sudo apt upgrade -y

          # Install Node.js, Python, Nginx, and PM2 if missing
          if ! command -v node &> /dev/null; then
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt install -y nodejs
          fi
          sudo apt install -y nginx python3 python3-pip
          sudo npm install -g pm2

          # Go to home directory
          cd /home/ubuntu

          # If repo folder doesn't exist, clone it
          if [ ! -d "project" ]; then
            git clone https://github.com/your-username/your-repo.git project
          fi

          # Go into project folder
          cd project
          git pull origin main

          # Install Node.js dependencies (if package.json exists)
          if [ -f "package.json" ]; then
            npm install || true
          fi

          # Install Python dependencies (if requirements.txt exists)
          if [ -f "requirements.txt" ]; then
            pip3 install -r requirements.txt || true
          fi

          # Restart Node and Flask apps
          pm2 delete nodeapp || true
          pm2 delete flaskapp || true

          # Start Node.js app
          pm2 start app.js --name nodeapp

          # Start Flask app
          pm2 start "python3 ai_model.py" --name flaskapp

          # Configure Nginx if not already configured
          if [ ! -f "/etc/nginx/sites-available/project-app" ]; then
            sudo bash -c 'cat > /etc/nginx/sites-available/project-app' <<EOF
server {
    listen 80;
    server_name 16.170.143.235;  # Replace with EC2 IP or domain

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_cache_bypass \$http_upgrade;
    }

    location /ai/ {
        proxy_pass http://localhost:5000/;
        proxy_set_header Host \$host;
    }
}
EOF
            sudo ln -s /etc/nginx/sites-available/project-app /etc/nginx/sites-enabled/
            sudo nginx -t
            sudo systemctl restart nginx
          fi

          # Save PM2 process list
          pm2 save
